Repository Tune-Manner/wisely-diary-frontend, pull requests merged in 2024-08, with the labels that each got.

#17 #13, #14 메인페이지(달력) 및 일기생성 페이지 일부 구현
  android/app/build.gradle
  assets/File plus.png
  assets/mic_img.png
  assets/stop_img.png
  assets/text_img.png
  assets/감사.png
  assets/걱정.png
  assets/당황.png
  assets/분노.png
  assets/뿌듯.png
  assets/설렘.png
  assets/슬픔.png
  assets/신나.png
  assets/억울.png
  assets/편안.png
  lib/add_photo_screens.dart
  lib/create_diary_screens.dart
  lib/diary_summary_screens.dart
  lib/home_screens.dart
  lib/main.dart
  lib/select_type_screens.dart
  lib/text_screens.dart
  lib/wait_screens.dart
  pubspec.yaml
Labels: frontend

#21 #4 custom scaffold 설정 및 마이페이지 구현
  lib/custom_scaffold.dart
  lib/diary_summary_screens.dart
  lib/home_screens.dart
  lib/login_screens.dart
  lib/main.dart
  lib/my_page.dart
Labels: UI, frontend, refactor

#23 #39 감정통계 월별 조회
  lib/alarm/alarm_setting_page.dart
  lib/home_screens.dart
  lib/main.dart
  lib/my_page.dart
  lib/statistics/monthly_emotion_screens.dart
  pubspec.yaml
Labels: frontend

#24 #12 이미지 여러장 업로드 기능 구현
  lib/add_photo_screens.dart
  pubspec.yaml
Labels: frontend

#25 #12 한번에 이미지 여러장 첨부할 수 있게 수정
  lib/add_photo_screens.dart
Labels: frontend, refactor

#26 #5 만화 생성 및 오늘 만화 조회
  .flutter-plugins
  .flutter-plugins-dependencies
  lib/add_photo_screens.dart
  lib/custom_scaffold.dart
  lib/diary_summary_screens.dart
  lib/home_screens.dart
  lib/main.dart
  lib/my_page.dart
  lib/record_screens.dart
  lib/statistics/monthly_emotion_screens.dart
  lib/today_cartoon.dart
  pubspec.lock
Labels: UI, frontend, refactor

#27 text를 통한 일기생성 페이지 구현
  android/app/src/main/AndroidManifest.xml
  lib/text_screens.dart
Labels: frontend

#28 #5 달력에서 만화 조회
  .flutter-plugins-dependencies
  lib/cartoon_inquery.dart
  lib/date_select.dart
  lib/home_screens.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: frontend

#31 #7 사용자 일기 상세 조회 버그 해결 및 스타일 변경
  lib/alarm/alarm_setting_page.dart
  lib/date_select.dart
  lib/statistics/monthly_emotion_screens.dart
Labels: bug, style

#32 #14 일기생성 시 STT 기능 구현
  lib/add_photo_screens.dart
  lib/diary_summary_screens.dart
  lib/main.dart
  lib/record_screens.dart
  lib/text_screens.dart
  lib/today_cartoon.dart
  pubspec.yaml
Labels: frontend

#33 #29 생성된 일기를 토대로 만화 생성
  .flutter-plugins
  .flutter-plugins-dependencies
  .idea/frontend.iml
  .idea/workspace.xml
  lib/add_photo_screens.dart
  lib/custom_scaffold.dart
  lib/date_select.dart
  lib/diary_summary_screens.dart
  lib/main.dart
  lib/record_screens.dart
  lib/select_type_screens.dart
  lib/text_screens.dart
  lib/today_cartoon.dart
  lib/wait_screens.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: frontend

#34 #14 record_screens design 수정
  lib/record_screens.dart
Labels: frontend

#36 #3 편지 생성 및 조회
  lib/diary_summary_screens.dart
  lib/letter/letter_creation_status_page.dart
  lib/letter/letter_model.dart
  lib/letter/letter_service.dart
  lib/letter/letter_view_page.dart
  lib/record_screens.dart
  lib/text_screens.dart
Labels: frontend

#37 #3 편지 생성 시 오류 해결
  lib/letter/letter_service.dart
  lib/letter/letter_view_page.dart
Labels: bug

#41 #38 일기 조회
  assets/emotions/greatful.png
  assets/emotions/proud.png
  assets/emotions/worried.png
  assets/감사.png
  assets/걱정.png
  assets/당황.png
  assets/분노.png
  assets/뿌듯.png
  assets/설렘.png
  assets/슬픔.png
  assets/신나.png
  assets/억울.png
  assets/편안.png
  lib/alarm/alarm_setting_page.dart
  lib/create_diary_screens.dart
  lib/home_screens.dart
  lib/main.dart
  lib/member_information.dart
  lib/statistics/monthly_emotion_screens.dart
  pubspec.yaml
Labels: bug, style, frontend, remove, merge

#42 #35 편지 만화 생성
  .flutter-plugins-dependencies
  .idea/workspace.xml
  lib/create_diary_screens.dart
  lib/home_screens.dart
  lib/letter/letter_creation_status_page.dart
  lib/letter/letter_view_page.dart
  lib/today_cartoon.dart
  lib/wait_screens.dart
Labels: UI, frontend, refactor

#43 #11 음악 생성 및 조회
  lib/diary_summary_screens.dart
  lib/music/music_creation_page.dart
  lib/music/music_player_page.dart
  lib/music/music_service.dart
  pubspec.yaml
Labels: frontend

#45 #38 일기 조회
  lib/custom_scaffold.dart
  lib/home_screens.dart
  lib/main.dart
Labels: bug, merge

#50 fix: 상세보기페이지 toggle 추가
  lib/date_select.dart
Labels: frontend

#53 #44 텍스트 입력 후 로딩 창 구현 및 햄버거 버튼 비활성화 구현
  .flutter-plugins-dependencies
  .idea/workspace.xml
  assets/deactive_cartoon_logo.png
  assets/deactive_letter_logo.png
  assets/deactive_music_logo.png
  lib/date_select.dart
  lib/diary_summary_screens.dart
  lib/home_screens.dart
  lib/record_screens.dart
  lib/text_screens.dart
  pubspec.yaml
Labels: frontend

#54 #52 일기 상세 페이지 연동 음악, 편지 조회 구현
  lib/date_select.dart
  lib/letter/letter_inquiry_page.dart
  lib/letter/letter_service.dart
  lib/music/music_inquiry_page.dart
  lib/music/music_service.dart
Labels: frontend

#55 fix: diarysummaryscreen에서 homescreen으로 이동간에 userId를 받지 못해 에러가 나는 오류 해…
  lib/add_photo_screens.dart
  lib/diary_summary_screens.dart
  lib/home_screens.dart
  lib/main.dart
  lib/record_screens.dart
Labels: frontend

#61 #14 일기 작성 페이지 벗어나면 음악 멈춤, 일기조회시 조건 추가
  lib/create_diary_screens.dart
  lib/date_select.dart
  lib/home_screens.dart
Labels: bug, frontend, refactor, merge

#62 #39 일기상세조회 오버레이 코드 누락 수정
  lib/cartoon_inquery.dart
  lib/date_select.dart
Labels: bug

#65 fix: add_photo_screens 에서 첨부한 이미지 서버로 업로드 기능 추가
  lib/add_photo_screens.dart
Labels: bug, frontend, refactor

#67 add_photo_screens 화면 수정
  lib/add_photo_screens.dart
Labels: UI, frontend

#68 이미지 등록시 등록된 이미지 확인 기능 추가
  lib/add_photo_screens.dart
Labels: frontend

#69 create README.md
  .gitattributes
  README.md
  lib/add_photo_screens.dart
  pubspec.lock
Labels: frontend
